/**This file will contain all the logic for all the reports to be generated by the api */
import lodash from 'lodash'

import Expense from "../models/Expenses.js";
import Lease from '../models/Lease.js';
import { returnTotal } from "../util/Calculation.js";
import { PAYMENTSTATUS } from '../util/Roles.js';
import { LEASE_STATUS } from '../util/types.js';

export const expenseReport = async (req, res) => {
  try {
    let allExpenses = await Expense.find({});
    
    let allExepensesGroups = lodash.groupBy(allExpenses,"type")

    let rtgsExpenses = allExepensesGroups['RTGS']
    let rtgsTotal = returnTotal(rtgsExpenses,"paidAmount")

    let usdExpenses = allExepensesGroups['USD']
    let usdTotal = returnTotal(usdExpenses,"paidAmount")


    
    

    // let totalExpenses = returnTotal(allExpenses, "paidAmount");

    res.status(201).json({
      success: true,
      messsage: "report successfully generated",
      data: {
        summary:{
            totalRTGS:rtgsTotal,
            totalUSD:usdTotal

        },
        expenses:{
            RTGSExepenses:rtgsExpenses,
            USDExpenses:usdExpenses
        },
      
      },
    });
  } catch (error) {
    console.log(error);
    res.status(501).json({
      success: false,
      messsage: error.messsage,
    });
  }
};


export const outstandingPayments = async (req, res) =>{

    try {
        let allOutStandingLeases =  await Lease.find({paymentStatus:LEASE_STATUS.OUTSTANDING})
        let outStandingTotal = returnTotal(allOutStandingLeases,"balance")

        res.status(201).json({
            success:true,
            message:"report successfully generated",
            data:{
                summary:{
                    totalOutstandingCount:allOutStandingLeases.length,
                    totalAmount:outStandingTotal
                },
                outStandings:allOutStandingLeases
                
            }
        })

    } catch (error) {
        
    }
}