/**This file will contain all the logic for all the reports to be generated by the api */
import lodash from 'lodash'

import Expense from "../models/Expenses.js";
import { returnTotal } from "../util/Calculation.js";

export const expenseReport = async (req, res) => {
  try {
    let allExpenses = await Expense.find({});
    
    let allExepensesGroups = lodash.groupBy(allExpenses,"type")

    let rtgsExpenses = allExepensesGroups['RTGS']
    let rtgsTotal = returnTotal(rtgsExpenses,"paidAmount")

    let usdExpenses = allExepensesGroups['USD']
    let usdTotal = returnTotal(usdExpenses,"paidAmount")


    
    

    // let totalExpenses = returnTotal(allExpenses, "paidAmount");

    res.status(201).json({
      success: true,
      messsage: "report successfully generated",
      data: {
        summary:{
            totalRTGS:rtgsTotal,
            totalUSD:usdTotal

        },
        expenses:{
            RTGSExepenses:rtgsExpenses,
            USDExpenses:usdExpenses
        },
      
      },
    });
  } catch (error) {
    console.log(error);
    res.status(501).json({
      success: false,
      messsage: error.messsage,
    });
  }
};
